### ISSUE TITLE
How to access the new API

### ISSUE THREAD

**Issue by jonasagx** [ArcadiaConsulting/appstorestats#12]
https://developers.googleblog.com/2016/03/introducing-google-api-console.html

This lib can no longer login to Google Play:
 com.github.andlyticsproject.console.AuthenticationException: Couldn't get developer account ID

**Comment by gonzalogomezgarcia** [comment]
We will have a look at it and try to reproduce it

**Comment by gonzalogomezgarcia** [comment]
We have validated the issue and created a branch for the Fix. New release 1.0.10 will be available shortly with the fix

**Comment by jonasagx** [comment]
Is there some documentation covering this google API to access statistics?

**Comment by gonzalogomezgarcia** [comment]
No, we don't have that kind of documentation yet. We have a long time issue regarding (#4 ) but we didn't find time to do it. If we manage to gather some time to do we will implement it. At least, I can give you a code snnipet on how to use the library: 
https://gist.github.com/gonzalogomezgarcia/815a0fad784e5f40898f85705b4f8cea
